language: php

# Which PHP versions we want to test
php:
  - 7.0
  - 5.6
  - 5.5

# Which versions are allowed to fail
matrix:
  allow_failures:
    - php: 7

# Which branches we want to test
branches:
  only:
    - master
    - develop
    - /^release-.*$/

# Which DBs we want to test
env:
  - DB=mysql
  - DB=postgres
  - DB=sqlite

before_script:
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install --dev --no-interaction
  # Setup for Selenium tests
  #- export DISPLAY=:99
  #- export WEB_FIXTURES_HOST=http://localhost
  #- export WEB_FIXTURES_BROWSER=firefox

  # Selenium first, give it time to boot..
  #- wget http://selenium.googlecode.com/files/selenium-server-standalone-2.28.0.jar
  #- java -jar selenium-server-standalone-2.28.0.jar > /dev/null &

  # Install dependencies
  #- sudo apt-get update
  #- sudo apt-get install -y --force-yes apache2 libapache2-mod-php5 php5-mysql
  #- sudo sed -i -e "s,/var/www,$(pwd)/wolfcms/tests/selenium,g" /etc/apache2/sites-available/default
  #- sudo /etc/init.d/apache2 restart

  # Install Wolf CMS files
  # todo

  # Setup rights for Wolf CMS files

  # Start up graphics
  #- sh -e /etc/init.d/xvfb start

  #- sleep 5

  # Run Wolf CMS Installer using Selenium
  #- sh -c "if [ '$DB' = 'postgres' ]; then psql -c 'DROP DATABASE IF EXISTS wolfcms_selenium;' -U postgres; fi"
  #- sh -c "if [ '$DB' = 'postgres' ]; then psql -c 'create database wolfcms_selenium;' -U postgres; fi"
  #- sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'DROP DATABASE IF EXISTS wolfcms_selenium;'; fi"
  #- sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'create database wolfcms_selenium;'; fi"
  # todo

  # Change admin password in DB
  #- sh -c "if [ '$DB' = 'postgres' ]; then psql -c 'UPDATE wolfcms_selenium SET password='TBD',salt='TDB' WHERE username=admin;' -U postgres; fi"
  #- sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'UPDATE wolfcms_selenium SET password='TBD',salt='TDB' WHERE username=admin;'; fi"

  # Setup fresh databases for PHPUnit tests
  - sh -c "if [ '$DB' = 'postgres' ]; then psql -c 'DROP DATABASE IF EXISTS wolfcms_test;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'postgres' ]; then psql -c 'create database wolfcms_test;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'DROP DATABASE IF EXISTS wolfcms_test;'; fi"
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'create database wolfcms_test;'; fi"

  # Clone the tests from the separate repo
  - git clone --depth=100 --quiet git://github.com/wolfcms/wolfcms-phpunit.git test

script:
  - cd test
  - mkdir -p build/logs
  - phpunit -c phpunit.travisci.xml

after_script:
  - cd ..
  # - php vendor/bin/coveralls --config test/.coveralls.yml -v

notifications:
  irc:
    channels:
      - "chat.freenode.net#wolfcms"
    on_success: change
    on_failure: change
